In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/dataset2.csv")
print(df.head())

                                                text     category  language
0    I need approval before I can close this ticket.  Work/Office   English
1  Isko behtar samajhne ke liye kahan dekhna chah...      General  Hinglish
2  The scenic overlook on the drive was worth the...       Travel   English
3  What are the eligibility criteria for this sch...      General   English
4  Manager ne presentation ko das slides tak shor...  Work/Office  Hinglish

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      1200 non-null   str
 1   category  1200 non-null   str
 2   language  1200 non-null   str
dtypes: str(3)
memory usage: 107.9 KB

In [4]:
print(df.shape)

(1200, 3)

In [5]:
print(df["category"].value_counts())

category
Work/Office    200
General        200
Travel         200
Mood           200
Complaint      200
Health         200
Name: count, dtype: int64

In [6]:
print(df["language"].value_counts())

language
English     600
Hinglish    600
Name: count, dtype: int64

In [7]:
print(
    pd.crosstab(
        df["category"],
        df["language"]
    )
)

language     English  Hinglish
category
Complaint        100       100
General          100       100
Health           100       100
Mood             100       100
Travel           100       100
Work/Office      100       100

In [8]:
df.sample(10, random_state=42)

                                                   text   category  language
1178   What's the process for applying to this program?    General   English
865   My refund request has been pending approval fo...  Complaint   English
101     Is scheme ke liye eligibility criteria kya hai?    General  Hinglish
439   Hotel stay bachane ke liye hum night bus le ra...     Travel  Hinglish
58    My account got locked and support isn't respon...  Complaint   English
1120  Repair ki wajah se road band tha, humein detou...     Travel  Hinglish
323   Package bilkul damaged aur bekaar condition me...  Complaint  Hinglish
974   Kai hafton baad chaal mein halkapan feel ho ra...       Mood  Hinglish
411   What are the steps to complete this registration?    General   English
855    Can you explain what these different tiers mean?    General   English

In [9]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    return text

In [10]:
df["clean_text"] = df["text"].apply(clean_text)

In [11]:
df[["text", "clean_text"]].head()

,text,clean_text
0,I need approval before I can close this ticket.,i need approval before i can close this ticket.
1,Isko behtar samajhne ke liye kahan dekhna chah...,isko behtar samajhne ke liye kahan dekhna chah...
2,The scenic overlook on the drive was worth the...,the scenic overlook on the drive was worth the...
3,What are the eligibility criteria for this sch...,what are the eligibility criteria for this sch...
4,Manager ne presentation ko das slides tak shor...,manager ne presentation ko das slides tak shor...

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [13]:
X = df["clean_text"]
y = df["category"]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [15]:
lr_pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=1,
        max_df=0.95,
        max_features=5000,
        sublinear_tf=True
    )),
    ("classifier", LogisticRegression(
        max_iter=1000,
        random_state=42
    ))
])

In [16]:
lr_pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.95, max_features=5000,
                                 ngram_range=(1, 2), sublinear_tf=True)),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

In [17]:
y_pred_lr = lr_pipeline.predict(X_test)

In [18]:
accuracy_lr = accuracy_score(y_test, y_pred_lr)
print("Logistic Regression Accuracy:", accuracy_lr)

Logistic Regression Accuracy: 0.875

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

from sklearn.naive_bayes import MultinomialNB

In [20]:
precision = precision_score(y_test, y_pred_lr, average="weighted")
recall = recall_score(y_test,y_pred_lr, average="weighted")
f1 = f1_score(y_test, y_pred_lr, average="weighted")

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.8732532970905065
Recall: 0.875
F1 Score: 0.8710127503353511

In [21]:
pipeline = Pipeline([
    ("tfidf", TfidfVectorizer()),
    ("nb", MultinomialNB())
])

In [22]:
param_grid = {

    "tfidf__ngram_range": [
        (1, 1),
        (1, 2)
    ],

    "tfidf__min_df": [
        1,
        2
    ],

    "tfidf__sublinear_tf": [
        True
    ],

    "nb__alpha": [
        0.01,
        0.1,
        0.5,
        1.0,
        2.0
    ]
}

In [23]:
grid_search = GridSearchCV(
    pipeline,
    param_grid,
    scoring="f1_weighted",
    cv=5,
    n_jobs=-1,
    verbose=1
)

In [24]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('tfidf', TfidfVectorizer()),
                                       ('nb', MultinomialNB())]),
             n_jobs=-1,
             param_grid={'nb__alpha': [0.01, 0.1, 0.5, 1.0, 2.0],
                         'tfidf__min_df': [1, 2],
                         'tfidf__ngram_range': [(1, 1), (1, 2)],
                         'tfidf__sublinear_tf': [True]},
             scoring='f1_weighted', verbose=1)

In [25]:
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

In [27]:
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

Accuracy : 0.9208
Precision: 0.9206
Recall   : 0.9208
F1 Score : 0.9189

In [28]:
final_model = grid_search.best_estimator_
final_model.fit(X, y)

Pipeline(steps=[('tfidf', TfidfVectorizer(sublinear_tf=True)),
                ('nb', MultinomialNB(alpha=0.01))])

In [29]:
import joblib
joblib.dump(
    final_model,
    "../models/category_model.pkl"
)

['../models/category_model.pkl']

In [30]:
X = df["clean_text"]
y = df["language"]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [32]:
language_pipeline = Pipeline([
    
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=1,
        max_df=0.95,
        max_features=5000,
        sublinear_tf=True
    )),
    
    ("classifier", MultinomialNB(
        alpha=1.0
    ))
])

In [33]:
language_pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.95, max_features=5000,
                                 ngram_range=(1, 2), sublinear_tf=True)),
                ('classifier', MultinomialNB())])

In [34]:
y_pred = language_pipeline.predict(X_test)

In [35]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

In [36]:
precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

In [37]:
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

Accuracy : 1.0000
Precision: 1.0000
Recall   : 1.0000
F1 Score : 1.0000

In [38]:
test_sentences = [
    # English
    "I am going to the office today.",
    "I am not feeling well today.",
    "Please send me the report by evening.",
    "I will join the meeting at ten o'clock.",
    "Can you help me with this task?",
    "I need to take a leave tomorrow.",
    "The project is almost completed.",
    "I am running late for the meeting.",
    "Please call me when you are free.",
    "I have completed my work for today.",

    # Hinglish
    "Mujhe aaj office jana hai.",
    "Aaj meri tabiyat thodi kharab hai.",
    "Please mujhe report shaam tak bhej dena.",
    "Main dus baje meeting join karunga.",
    "Kya tum meri help kar sakte ho?",
    "Mujhe kal leave leni hai.",
    "Project almost complete ho gaya hai.",
    "Main meeting ke liye late ho raha hoon.",
    "Jab tum free ho mujhe call karna.",
    "Maine aaj ka kaam complete kar liya hai."
]

for text in test_sentences:

    probabilities = language_pipeline.predict_proba([text])[0]

    prediction = language_pipeline.predict([text])[0]

    confidence = max(probabilities)

    print("----------------------------------------")
    print("Text:", text)
    print("Language:", prediction)
    print(f"Confidence: {confidence * 100:.2f}%")

----------------------------------------
Text: I am going to the office today.
Language: English
Confidence: 95.11%
----------------------------------------
Text: I am not feeling well today.
Language: English
Confidence: 88.10%
----------------------------------------
Text: Please send me the report by evening.
Language: English
Confidence: 84.88%
----------------------------------------
Text: I will join the meeting at ten o'clock.
Language: English
Confidence: 90.72%
----------------------------------------
Text: Can you help me with this task?
Language: English
Confidence: 98.29%
----------------------------------------
Text: I need to take a leave tomorrow.
Language: English
Confidence: 95.82%
----------------------------------------
Text: The project is almost completed.
Language: English
Confidence: 75.59%
----------------------------------------
Text: I am running late for the meeting.
Language: English
Confidence: 92.56%
----------------------------------------
Text: Please call me when you are free.
Language: English
Confidence: 89.00%
----------------------------------------
Text: I have completed my work for today.
Language: English
Confidence: 96.29%
----------------------------------------
Text: Mujhe aaj office jana hai.
Language: Hinglish
Confidence: 91.97%
----------------------------------------
Text: Aaj meri tabiyat thodi kharab hai.
Language: Hinglish
Confidence: 93.36%
----------------------------------------
Text: Please mujhe report shaam tak bhej dena.
Language: Hinglish
Confidence: 83.92%
----------------------------------------
Text: Main dus baje meeting join karunga.
Language: Hinglish
Confidence: 54.17%
----------------------------------------
Text: Kya tum meri help kar sakte ho?
Language: Hinglish
Confidence: 97.75%
----------------------------------------
Text: Mujhe kal leave leni hai.
Language: Hinglish
Confidence: 85.59%
----------------------------------------
Text: Project almost complete ho gaya hai.
Language: Hinglish
Confidence: 96.08%
----------------------------------------
Text: Main meeting ke liye late ho raha hoon.
Language: Hinglish
Confidence: 98.27%
----------------------------------------
Text: Jab tum free ho mujhe call karna.
Language: Hinglish
Confidence: 84.82%
----------------------------------------
Text: Maine aaj ka kaam complete kar liya hai.
Language: Hinglish
Confidence: 95.86%

In [39]:
language_pipeline.fit(X, y)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_df=0.95, max_features=5000,
                                 ngram_range=(1, 2), sublinear_tf=True)),
                ('classifier', MultinomialNB())])

In [40]:
joblib.dump(
    language_pipeline,
    "../models/language_model.pkl"
)

['../models/language_model.pkl']